pub(crate) const SDKWORK_CONFIG_DIR: &str = "SDKWORK_CONFIG_DIR";
pub(crate) const SDKWORK_CONFIG_FILE: &str = "SDKWORK_CONFIG_FILE";
pub(crate) const SDKWORK_GATEWAY_BIND: &str = "SDKWORK_GATEWAY_BIND";
pub(crate) const SDKWORK_ADMIN_BIND: &str = "SDKWORK_ADMIN_BIND";
pub(crate) const SDKWORK_PORTAL_BIND: &str = "SDKWORK_PORTAL_BIND";
pub(crate) const SDKWORK_DATABASE_URL: &str = "SDKWORK_DATABASE_URL";
pub(crate) const SDKWORK_CACHE_BACKEND: &str = "SDKWORK_CACHE_BACKEND";
pub(crate) const SDKWORK_CACHE_URL: &str = "SDKWORK_CACHE_URL";
pub(crate) const SDKWORK_EXTENSION_PATHS: &str = "SDKWORK_EXTENSION_PATHS";
pub(crate) const SDKWORK_EXTENSION_ENABLE_CONNECTOR_EXTENSIONS: &str =
    "SDKWORK_EXTENSION_ENABLE_CONNECTOR_EXTENSIONS";
pub(crate) const SDKWORK_EXTENSION_ENABLE_NATIVE_DYNAMIC_EXTENSIONS: &str =
    "SDKWORK_EXTENSION_ENABLE_NATIVE_DYNAMIC_EXTENSIONS";
pub(crate) const SDKWORK_EXTENSION_HOT_RELOAD_INTERVAL_SECS: &str =
    "SDKWORK_EXTENSION_HOT_RELOAD_INTERVAL_SECS";
pub(crate) const SDKWORK_EXTENSION_TRUSTED_SIGNERS: &str = "SDKWORK_EXTENSION_TRUSTED_SIGNERS";
pub(crate) const SDKWORK_EXTENSION_REQUIRE_SIGNATURE_FOR_CONNECTOR_EXTENSIONS: &str =
    "SDKWORK_EXTENSION_REQUIRE_SIGNATURE_FOR_CONNECTOR_EXTENSIONS";
pub(crate) const SDKWORK_EXTENSION_REQUIRE_SIGNATURE_FOR_NATIVE_DYNAMIC_EXTENSIONS: &str =
    "SDKWORK_EXTENSION_REQUIRE_SIGNATURE_FOR_NATIVE_DYNAMIC_EXTENSIONS";
pub(crate) const SDKWORK_NATIVE_DYNAMIC_SHUTDOWN_DRAIN_TIMEOUT_MS: &str =
    "SDKWORK_NATIVE_DYNAMIC_SHUTDOWN_DRAIN_TIMEOUT_MS";
pub(crate) const SDKWORK_ADMIN_JWT_SIGNING_SECRET: &str = "SDKWORK_ADMIN_JWT_SIGNING_SECRET";
pub(crate) const SDKWORK_PORTAL_JWT_SIGNING_SECRET: &str = "SDKWORK_PORTAL_JWT_SIGNING_SECRET";
pub(crate) const SDKWORK_RUNTIME_SNAPSHOT_INTERVAL_SECS: &str =
    "SDKWORK_RUNTIME_SNAPSHOT_INTERVAL_SECS";
pub(crate) const SDKWORK_PRICING_LIFECYCLE_SYNC_INTERVAL_SECS: &str =
    "SDKWORK_PRICING_LIFECYCLE_SYNC_INTERVAL_SECS";
pub(crate) const SDKWORK_SECRET_BACKEND: &str = "SDKWORK_SECRET_BACKEND";
pub(crate) const SDKWORK_CREDENTIAL_MASTER_KEY: &str = "SDKWORK_CREDENTIAL_MASTER_KEY";
pub(crate) const SDKWORK_CREDENTIAL_LEGACY_MASTER_KEYS: &str =
    "SDKWORK_CREDENTIAL_LEGACY_MASTER_KEYS";
pub(crate) const SDKWORK_SECRET_LOCAL_FILE: &str = "SDKWORK_SECRET_LOCAL_FILE";
pub(crate) const SDKWORK_SECRET_KEYRING_SERVICE: &str = "SDKWORK_SECRET_KEYRING_SERVICE";
pub(crate) const SDKWORK_ALLOW_INSECURE_DEV_DEFAULTS: &str = "SDKWORK_ALLOW_INSECURE_DEV_DEFAULTS";
pub(crate) const SDKWORK_METRICS_BEARER_TOKEN: &str = "SDKWORK_METRICS_BEARER_TOKEN";
pub(crate) const SDKWORK_BROWSER_ALLOWED_ORIGINS: &str = "SDKWORK_BROWSER_ALLOWED_ORIGINS";

pub(crate) const DEFAULT_ADMIN_JWT_SIGNING_SECRET: &str = "local-dev-admin-jwt-secret";
pub(crate) const DEFAULT_PORTAL_JWT_SIGNING_SECRET: &str = "local-dev-portal-jwt-secret";
pub(crate) const DEFAULT_CREDENTIAL_MASTER_KEY: &str = "local-dev-master-key";
pub(crate) const DEFAULT_METRICS_BEARER_TOKEN: &str = "local-dev-metrics-token";
pub(crate) const DEFAULT_BROWSER_ALLOWED_ORIGINS: [&str; 8] = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
];

pub(crate) const MANAGED_ENV_KEYS: [&str; 23] = [
    SDKWORK_GATEWAY_BIND,
    SDKWORK_ADMIN_BIND,
    SDKWORK_PORTAL_BIND,
    SDKWORK_DATABASE_URL,
    SDKWORK_CACHE_BACKEND,
    SDKWORK_CACHE_URL,
    SDKWORK_EXTENSION_PATHS,
    SDKWORK_EXTENSION_ENABLE_CONNECTOR_EXTENSIONS,
    SDKWORK_EXTENSION_ENABLE_NATIVE_DYNAMIC_EXTENSIONS,
    SDKWORK_EXTENSION_HOT_RELOAD_INTERVAL_SECS,
    SDKWORK_EXTENSION_TRUSTED_SIGNERS,
    SDKWORK_EXTENSION_REQUIRE_SIGNATURE_FOR_CONNECTOR_EXTENSIONS,
    SDKWORK_EXTENSION_REQUIRE_SIGNATURE_FOR_NATIVE_DYNAMIC_EXTENSIONS,
    SDKWORK_NATIVE_DYNAMIC_SHUTDOWN_DRAIN_TIMEOUT_MS,
    SDKWORK_ADMIN_JWT_SIGNING_SECRET,
    SDKWORK_PORTAL_JWT_SIGNING_SECRET,
    SDKWORK_RUNTIME_SNAPSHOT_INTERVAL_SECS,
    SDKWORK_PRICING_LIFECYCLE_SYNC_INTERVAL_SECS,
    SDKWORK_SECRET_BACKEND,
    SDKWORK_CREDENTIAL_MASTER_KEY,
    SDKWORK_ALLOW_INSECURE_DEV_DEFAULTS,
    SDKWORK_METRICS_BEARER_TOKEN,
    SDKWORK_BROWSER_ALLOWED_ORIGINS,
];

pub(crate) const MANAGED_SECRET_ENV_KEYS: [&str; 3] = [
    SDKWORK_CREDENTIAL_LEGACY_MASTER_KEYS,
    SDKWORK_SECRET_LOCAL_FILE,
    SDKWORK_SECRET_KEYRING_SERVICE,
];
