#![allow(clippy::await_holding_lock)]

use axum::body::{to_bytes, Body};
use axum::http::{Request, StatusCode};
use std::sync::{Mutex, OnceLock};
use tower::ServiceExt;

fn http_exposure_env_lock() -> &'static Mutex<()> {
    static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
    LOCK.get_or_init(|| Mutex::new(()))
}

#[tokio::test]
async fn openapi_routes_expose_gateway_api_inventory() {
    let _lock = http_exposure_env_lock().lock().unwrap();
    let app = sdkwork_api_interface_http::gateway_router();

    let openapi = app
        .clone()
        .oneshot(
            Request::builder()
                .uri("/openapi.json")
                .body(Body::empty())
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(openapi.status(), StatusCode::OK);
    let bytes = to_bytes(openapi.into_body(), usize::MAX).await.unwrap();
    let json: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
    assert_eq!(json["openapi"], "3.1.0");
    assert_eq!(json["info"]["title"], "SDKWORK Gateway API");
    assert!(json["paths"]["/health"]["get"].is_object());
    assert!(json["paths"]["/market/products"]["get"].is_object());
    assert!(json["paths"]["/market/offers"]["get"].is_object());
    assert!(json["paths"]["/market/quotes"]["post"].is_object());
    assert!(json["paths"]["/marketing/coupons/validate"]["post"].is_object());
    assert!(json["paths"]["/marketing/coupons/reserve"]["post"].is_object());
    assert!(json["paths"]["/marketing/coupons/confirm"]["post"].is_object());
    assert!(json["paths"]["/marketing/coupons/rollback"]["post"].is_object());
    assert!(json["paths"]["/commercial/account"]["get"].is_object());
    assert!(json["paths"]["/commercial/account/benefit-lots"]["get"].is_object());
    assert!(json["paths"]["/v1/models"]["get"].is_object());
    assert!(json["paths"]["/v1/models/{model_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/chat/completions"]["post"].is_object());
    assert!(json["paths"]["/v1/completions"]["post"].is_object());
    assert!(json["paths"]["/v1/responses"]["post"].is_object());
    assert!(json["paths"]["/v1/responses/input_tokens"]["post"].is_object());
    assert!(json["paths"]["/v1/responses/compact"]["post"].is_object());
    assert!(json["paths"]["/v1/responses/{response_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/responses/{response_id}"]["delete"].is_object());
    assert!(json["paths"]["/v1/responses/{response_id}/input_items"]["get"].is_object());
    assert!(json["paths"]["/v1/responses/{response_id}/cancel"]["post"].is_object());
    assert!(json["paths"]["/v1/embeddings"]["post"].is_object());
    assert!(json["paths"]["/v1/conversations"]["get"].is_object());
    assert!(json["paths"]["/v1/conversations"]["post"].is_object());
    assert!(json["paths"]["/v1/conversations/{conversation_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/conversations/{conversation_id}"]["post"].is_object());
    assert!(json["paths"]["/v1/conversations/{conversation_id}"]["delete"].is_object());
    assert!(json["paths"]["/v1/conversations/{conversation_id}/items"]["get"].is_object());
    assert!(json["paths"]["/v1/conversations/{conversation_id}/items"]["post"].is_object());
    assert!(
        json["paths"]["/v1/conversations/{conversation_id}/items/{item_id}"]["get"].is_object()
    );
    assert!(
        json["paths"]["/v1/conversations/{conversation_id}/items/{item_id}"]["delete"].is_object()
    );
    assert!(json["paths"]["/v1/moderations"]["post"].is_object());
    assert!(json["paths"]["/v1/images/generations"]["post"].is_object());
    assert!(json["paths"]["/v1/images/edits"]["post"].is_object());
    assert!(json["paths"]["/v1/images/variations"]["post"].is_object());
    assert!(json["paths"]["/v1/audio/transcriptions"]["post"].is_object());
    assert!(json["paths"]["/v1/audio/translations"]["post"].is_object());
    assert!(json["paths"]["/v1/audio/speech"]["post"].is_object());
    assert!(json["paths"]["/v1/audio/voices"]["get"].is_object());
    assert!(json["paths"]["/v1/audio/voice_consents"]["post"].is_object());
    assert!(json["paths"]["/v1/assistants"]["get"].is_object());
    assert!(json["paths"]["/v1/assistants"]["post"].is_object());
    assert!(json["paths"]["/v1/assistants/{assistant_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/realtime/sessions"]["post"].is_object());
    assert!(json["paths"]["/v1/files"]["get"].is_object());
    assert!(json["paths"]["/v1/files"]["post"].is_object());
    assert!(json["paths"]["/v1/files/{file_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/files/{file_id}"]["delete"].is_object());
    assert!(json["paths"]["/v1/uploads"]["post"].is_object());
    assert!(json["paths"]["/v1/uploads/{upload_id}/parts"]["post"].is_object());
    assert!(json["paths"]["/v1/uploads/{upload_id}/complete"]["post"].is_object());
    assert!(json["paths"]["/v1/uploads/{upload_id}/cancel"]["post"].is_object());
    assert!(json["paths"]["/v1/batches"]["get"].is_object());
    assert!(json["paths"]["/v1/batches"]["post"].is_object());
    assert!(json["paths"]["/v1/batches/{batch_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/batches/{batch_id}/cancel"]["post"].is_object());
    assert!(json["paths"]["/v1/vector_stores"]["get"].is_object());
    assert!(json["paths"]["/v1/vector_stores"]["post"].is_object());
    assert!(json["paths"]["/v1/vector_stores/{vector_store_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/vector_stores/{vector_store_id}"]["post"].is_object());
    assert!(json["paths"]["/v1/vector_stores/{vector_store_id}"]["delete"].is_object());
    assert!(json["paths"]["/v1/vector_stores/{vector_store_id}/search"]["post"].is_object());
    assert!(json["paths"]["/v1/vector_stores/{vector_store_id}/files"]["get"].is_object());
    assert!(json["paths"]["/v1/vector_stores/{vector_store_id}/files"]["post"].is_object());
    assert!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/files/{file_id}"]["get"].is_object()
    );
    assert!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/files/{file_id}"]["delete"].is_object()
    );
    assert!(json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches"]["post"].is_object());
    assert!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}"]["get"]
            .is_object()
    );
    assert!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/cancel"]["post"]
            .is_object()
    );
    assert!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/files"]["get"]
            .is_object()
    );
    assert!(json["paths"]["/v1/threads"]["post"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}"]["post"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}"]["delete"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/messages"]["get"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/messages"]["post"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/messages/{message_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/messages/{message_id}"]["post"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/messages/{message_id}"]["delete"].is_object());
    assert!(json["paths"]["/v1/threads/runs"]["post"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/runs"]["get"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/runs"]["post"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/runs/{run_id}"]["get"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/runs/{run_id}"]["post"].is_object());
    assert!(json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/cancel"]["post"].is_object());
    assert!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs"]["post"]
            .is_object()
    );
    assert!(json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/steps"]["get"].is_object());
    assert!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/steps/{step_id}"]["get"].is_object()
    );
    assert!(json["paths"]["/v1/messages"]["post"].is_object());
    assert!(json["paths"]["/v1/messages/count_tokens"]["post"].is_object());
    assert!(json["paths"]["/v1beta/models/{tail}"]["post"].is_object());
    assert!(json["components"]["schemas"].is_object());
    assert!(json["components"]["schemas"]["ListModelsResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayMarketProductsResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayMarketOffersResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponValidationRequest"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponValidationResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponReservationRequest"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponReservationResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponRedemptionConfirmRequest"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponRedemptionConfirmResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponRedemptionRollbackRequest"].is_object());
    assert!(json["components"]["schemas"]["GatewayCouponRedemptionRollbackResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayCommercialAccountResponse"].is_object());
    assert!(json["components"]["schemas"]["GatewayCommercialBenefitLotsResponse"].is_object());
    assert!(json["components"]["schemas"]["ModelObject"].is_object());
    assert!(json["components"]["schemas"]["CreateChatCompletionRequest"].is_object());
    assert!(json["components"]["schemas"]["ChatCompletionResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateCompletionRequest"].is_object());
    assert!(json["components"]["schemas"]["CompletionObject"].is_object());
    assert!(json["components"]["schemas"]["CreateResponseRequest"].is_object());
    assert!(json["components"]["schemas"]["ResponseObject"].is_object());
    assert!(json["components"]["schemas"]["CountResponseInputTokensRequest"].is_object());
    assert!(json["components"]["schemas"]["ResponseInputTokensObject"].is_object());
    assert!(json["components"]["schemas"]["CompactResponseRequest"].is_object());
    assert!(json["components"]["schemas"]["ResponseCompactionObject"].is_object());
    assert!(json["components"]["schemas"]["ResponseInputItemObject"].is_object());
    assert!(json["components"]["schemas"]["ListResponseInputItemsResponse"].is_object());
    assert!(json["components"]["schemas"]["DeleteResponseResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateEmbeddingRequest"].is_object());
    assert!(json["components"]["schemas"]["CreateEmbeddingResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateModerationRequest"].is_object());
    assert!(json["components"]["schemas"]["ModerationResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateImageRequest"].is_object());
    assert!(json["components"]["schemas"]["CreateImageEditRequest"].is_object());
    assert!(json["components"]["schemas"]["CreateImageVariationRequest"].is_object());
    assert!(json["components"]["schemas"]["ImagesResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateTranscriptionRequest"].is_object());
    assert!(json["components"]["schemas"]["TranscriptionObject"].is_object());
    assert!(json["components"]["schemas"]["CreateTranslationRequest"].is_object());
    assert!(json["components"]["schemas"]["TranslationObject"].is_object());
    assert!(json["components"]["schemas"]["CreateSpeechRequest"].is_object());
    assert!(json["components"]["schemas"]["SpeechResponse"].is_object());
    assert!(json["components"]["schemas"]["ListVoicesResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateVoiceConsentRequest"].is_object());
    assert!(json["components"]["schemas"]["VoiceConsentObject"].is_object());
    assert!(json["components"]["schemas"]["CreateAssistantRequest"].is_object());
    assert!(json["components"]["schemas"]["AssistantObject"].is_object());
    assert!(json["components"]["schemas"]["ListAssistantsResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateRealtimeSessionRequest"].is_object());
    assert!(json["components"]["schemas"]["RealtimeSessionObject"].is_object());
    assert!(json["components"]["schemas"]["CreateFileRequest"].is_object());
    assert!(json["components"]["schemas"]["FileObject"].is_object());
    assert!(json["components"]["schemas"]["ListFilesResponse"].is_object());
    assert!(json["components"]["schemas"]["DeleteFileResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateUploadRequest"].is_object());
    assert!(json["components"]["schemas"]["AddUploadPartRequest"].is_object());
    assert!(json["components"]["schemas"]["CompleteUploadRequest"].is_object());
    assert!(json["components"]["schemas"]["UploadObject"].is_object());
    assert!(json["components"]["schemas"]["UploadPartObject"].is_object());
    assert!(json["components"]["schemas"]["CreateBatchRequest"].is_object());
    assert!(json["components"]["schemas"]["BatchObject"].is_object());
    assert!(json["components"]["schemas"]["ListBatchesResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateVectorStoreRequest"].is_object());
    assert!(json["components"]["schemas"]["UpdateVectorStoreRequest"].is_object());
    assert!(json["components"]["schemas"]["VectorStoreObject"].is_object());
    assert!(json["components"]["schemas"]["ListVectorStoresResponse"].is_object());
    assert!(json["components"]["schemas"]["DeleteVectorStoreResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateVectorStoreFileRequest"].is_object());
    assert!(json["components"]["schemas"]["VectorStoreFileObject"].is_object());
    assert!(json["components"]["schemas"]["ListVectorStoreFilesResponse"].is_object());
    assert!(json["components"]["schemas"]["DeleteVectorStoreFileResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateVectorStoreFileBatchRequest"].is_object());
    assert!(json["components"]["schemas"]["VectorStoreFileBatchObject"].is_object());
    assert!(json["components"]["schemas"]["SearchVectorStoreRequest"].is_object());
    assert!(json["components"]["schemas"]["SearchVectorStoreResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateConversationRequest"].is_object());
    assert!(json["components"]["schemas"]["UpdateConversationRequest"].is_object());
    assert!(json["components"]["schemas"]["CreateConversationItemsRequest"].is_object());
    assert!(json["components"]["schemas"]["ConversationObject"].is_object());
    assert!(json["components"]["schemas"]["ListConversationsResponse"].is_object());
    assert!(json["components"]["schemas"]["DeleteConversationResponse"].is_object());
    assert!(json["components"]["schemas"]["ConversationItemObject"].is_object());
    assert!(json["components"]["schemas"]["ListConversationItemsResponse"].is_object());
    assert!(json["components"]["schemas"]["DeleteConversationItemResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateThreadRequest"].is_object());
    assert!(json["components"]["schemas"]["UpdateThreadRequest"].is_object());
    assert!(json["components"]["schemas"]["ThreadObject"].is_object());
    assert!(json["components"]["schemas"]["DeleteThreadResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateThreadMessageRequest"].is_object());
    assert!(json["components"]["schemas"]["UpdateThreadMessageRequest"].is_object());
    assert!(json["components"]["schemas"]["ThreadMessageObject"].is_object());
    assert!(json["components"]["schemas"]["ListThreadMessagesResponse"].is_object());
    assert!(json["components"]["schemas"]["DeleteThreadMessageResponse"].is_object());
    assert!(json["components"]["schemas"]["CreateRunRequest"].is_object());
    assert!(json["components"]["schemas"]["CreateThreadAndRunRequest"].is_object());
    assert!(json["components"]["schemas"]["UpdateRunRequest"].is_object());
    assert!(json["components"]["schemas"]["RunToolOutput"].is_object());
    assert!(json["components"]["schemas"]["SubmitToolOutputsRunRequest"].is_object());
    assert!(json["components"]["schemas"]["RunObject"].is_object());
    assert!(json["components"]["schemas"]["ListRunsResponse"].is_object());
    assert!(json["components"]["schemas"]["RunStepObject"].is_object());
    assert!(json["components"]["schemas"]["ListRunStepsResponse"].is_object());
    assert!(json["components"]["schemas"]["OpenAiErrorResponse"].is_object());
    assert_eq!(
        json["paths"]["/market/products"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/GatewayMarketProductsResponse"
    );
    assert_eq!(
        json["paths"]["/market/offers"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/GatewayMarketOffersResponse"
    );
    assert_eq!(
        json["paths"]["/market/quotes"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/PortalCommerceQuoteRequest"
    );
    assert_eq!(
        json["paths"]["/market/quotes"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/PortalCommerceQuote"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/validate"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponValidationRequest"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/validate"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponValidationResponse"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/reserve"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponReservationRequest"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/reserve"]["post"]["responses"]["201"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponReservationResponse"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/confirm"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponRedemptionConfirmRequest"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/confirm"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponRedemptionConfirmResponse"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/rollback"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponRedemptionRollbackRequest"
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/rollback"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCouponRedemptionRollbackResponse"
    );
    assert_eq!(
        json["paths"]["/commercial/account"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCommercialAccountResponse"
    );
    assert_eq!(
        json["paths"]["/commercial/account/benefit-lots"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/GatewayCommercialBenefitLotsResponse"
    );
    assert_eq!(
        json["paths"]["/commercial/account/benefit-lots"]["get"]["parameters"][0]["name"],
        "after_lot_id"
    );
    assert_eq!(
        json["paths"]["/commercial/account/benefit-lots"]["get"]["parameters"][1]["name"],
        "limit"
    );
    assert_eq!(
        json["paths"]["/v1/models"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ListModelsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/models/{model_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ModelObject"
    );
    assert_eq!(
        json["paths"]["/v1/chat/completions"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateChatCompletionRequest"
    );
    assert_eq!(
        json["paths"]["/v1/chat/completions"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ChatCompletionResponse"
    );
    assert_eq!(
        json["paths"]["/v1/completions"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateCompletionRequest"
    );
    assert_eq!(
        json["paths"]["/v1/completions"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CompletionObject"
    );
    assert_eq!(
        json["paths"]["/v1/responses"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateResponseRequest"
    );
    assert_eq!(
        json["paths"]["/v1/responses"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ResponseObject"
    );
    assert_eq!(
        json["paths"]["/v1/responses/input_tokens"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CountResponseInputTokensRequest"
    );
    assert_eq!(
        json["paths"]["/v1/responses/input_tokens"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ResponseInputTokensObject"
    );
    assert_eq!(
        json["paths"]["/v1/responses/compact"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CompactResponseRequest"
    );
    assert_eq!(
        json["paths"]["/v1/responses/compact"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ResponseCompactionObject"
    );
    assert_eq!(
        json["paths"]["/v1/responses/{response_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ResponseObject"
    );
    assert_eq!(
        json["paths"]["/v1/responses/{response_id}"]["delete"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteResponseResponse"
    );
    assert_eq!(
        json["paths"]["/v1/responses/{response_id}/input_items"]["get"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListResponseInputItemsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/responses/{response_id}/cancel"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ResponseObject"
    );
    assert_eq!(
        json["paths"]["/v1/embeddings"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateEmbeddingRequest"
    );
    assert_eq!(
        json["paths"]["/v1/embeddings"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateEmbeddingResponse"
    );
    assert_eq!(
        json["paths"]["/v1/moderations"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateModerationRequest"
    );
    assert_eq!(
        json["paths"]["/v1/moderations"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ModerationResponse"
    );
    assert_eq!(
        json["paths"]["/v1/images/generations"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateImageRequest"
    );
    assert_eq!(
        json["paths"]["/v1/images/generations"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ImagesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/images/edits"]["post"]["requestBody"]["content"]["multipart/form-data"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateImageEditRequest"
    );
    assert_eq!(
        json["paths"]["/v1/images/edits"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ImagesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/images/variations"]["post"]["requestBody"]["content"]
            ["multipart/form-data"]["schema"]["$ref"],
        "#/components/schemas/CreateImageVariationRequest"
    );
    assert_eq!(
        json["paths"]["/v1/images/variations"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ImagesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/audio/transcriptions"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateTranscriptionRequest"
    );
    assert_eq!(
        json["paths"]["/v1/audio/transcriptions"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/TranscriptionObject"
    );
    assert_eq!(
        json["paths"]["/v1/audio/translations"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateTranslationRequest"
    );
    assert_eq!(
        json["paths"]["/v1/audio/translations"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/TranslationObject"
    );
    assert_eq!(
        json["paths"]["/v1/audio/speech"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateSpeechRequest"
    );
    assert_eq!(
        json["paths"]["/v1/audio/speech"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/SpeechResponse"
    );
    assert_eq!(
        json["paths"]["/v1/audio/voices"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ListVoicesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/audio/voice_consents"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateVoiceConsentRequest"
    );
    assert_eq!(
        json["paths"]["/v1/audio/voice_consents"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/VoiceConsentObject"
    );
    assert_eq!(
        json["paths"]["/v1/assistants"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ListAssistantsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/assistants"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateAssistantRequest"
    );
    assert_eq!(
        json["paths"]["/v1/assistants"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/AssistantObject"
    );
    assert_eq!(
        json["paths"]["/v1/assistants/{assistant_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/AssistantObject"
    );
    assert_eq!(
        json["paths"]["/v1/realtime/sessions"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateRealtimeSessionRequest"
    );
    assert_eq!(
        json["paths"]["/v1/realtime/sessions"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/RealtimeSessionObject"
    );
    assert_eq!(
        json["paths"]["/v1/files"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ListFilesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/files"]["post"]["requestBody"]["content"]["multipart/form-data"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateFileRequest"
    );
    assert_eq!(
        json["paths"]["/v1/files"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/FileObject"
    );
    assert_eq!(
        json["paths"]["/v1/files/{file_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/FileObject"
    );
    assert_eq!(
        json["paths"]["/v1/files/{file_id}"]["delete"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteFileResponse"
    );
    assert_eq!(
        json["paths"]["/v1/uploads"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateUploadRequest"
    );
    assert_eq!(
        json["paths"]["/v1/uploads"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/UploadObject"
    );
    assert_eq!(
        json["paths"]["/v1/uploads/{upload_id}/parts"]["post"]["requestBody"]["content"]
            ["multipart/form-data"]["schema"]["$ref"],
        "#/components/schemas/AddUploadPartRequest"
    );
    assert_eq!(
        json["paths"]["/v1/uploads/{upload_id}/parts"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/UploadPartObject"
    );
    assert_eq!(
        json["paths"]["/v1/uploads/{upload_id}/complete"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CompleteUploadRequest"
    );
    assert_eq!(
        json["paths"]["/v1/uploads/{upload_id}/complete"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/UploadObject"
    );
    assert_eq!(
        json["paths"]["/v1/uploads/{upload_id}/cancel"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/UploadObject"
    );
    assert_eq!(
        json["paths"]["/v1/batches"]["get"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ListBatchesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/batches"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateBatchRequest"
    );
    assert_eq!(
        json["paths"]["/v1/batches"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/BatchObject"
    );
    assert_eq!(
        json["paths"]["/v1/batches/{batch_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/BatchObject"
    );
    assert_eq!(
        json["paths"]["/v1/batches/{batch_id}/cancel"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/BatchObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListVectorStoresResponse"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateVectorStoreRequest"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/UpdateVectorStoreRequest"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}"]["delete"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteVectorStoreResponse"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/search"]["post"]["requestBody"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/SearchVectorStoreRequest"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/search"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/SearchVectorStoreResponse"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/files"]["get"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListVectorStoreFilesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/files"]["post"]["requestBody"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateVectorStoreFileRequest"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/files"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreFileObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/files/{file_id}"]["get"]["responses"]
            ["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreFileObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/files/{file_id}"]["delete"]["responses"]
            ["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteVectorStoreFileResponse"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches"]["post"]["requestBody"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateVectorStoreFileBatchRequest"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches"]["post"]["responses"]
            ["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreFileBatchObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}"]["get"]
            ["responses"]["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreFileBatchObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/cancel"]["post"]
            ["responses"]["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/VectorStoreFileBatchObject"
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/file_batches/{batch_id}/files"]["get"]
            ["responses"]["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListVectorStoreFilesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/conversations"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListConversationsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/conversations"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateConversationRequest"
    );
    assert_eq!(
        json["paths"]["/v1/conversations"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ConversationObject"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ConversationObject"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/UpdateConversationRequest"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ConversationObject"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}"]["delete"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteConversationResponse"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}/items"]["get"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListConversationItemsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}/items"]["post"]["requestBody"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateConversationItemsRequest"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}/items"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListConversationItemsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}/items/{item_id}"]["get"]["responses"]
            ["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ConversationItemObject"
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}/items/{item_id}"]["delete"]["responses"]
            ["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteConversationItemResponse"
    );
    assert_eq!(
        json["paths"]["/v1/threads"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateThreadRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads"]["post"]["responses"]["200"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/ThreadObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ThreadObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/UpdateThreadRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ThreadObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}"]["delete"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteThreadResponse"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListThreadMessagesResponse"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateThreadMessageRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ThreadMessageObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages/{message_id}"]["get"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ThreadMessageObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages/{message_id}"]["post"]["requestBody"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/UpdateThreadMessageRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages/{message_id}"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ThreadMessageObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages/{message_id}"]["delete"]["responses"]
            ["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/DeleteThreadMessageResponse"
    );
    assert_eq!(
        json["paths"]["/v1/threads/runs"]["post"]["requestBody"]["content"]["application/json"]
            ["schema"]["$ref"],
        "#/components/schemas/CreateThreadAndRunRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads/runs"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/RunObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs"]["get"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListRunsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/CreateRunRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs"]["post"]["responses"]["200"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/RunObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}"]["get"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/RunObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}"]["post"]["requestBody"]["content"]
            ["application/json"]["schema"]["$ref"],
        "#/components/schemas/UpdateRunRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/RunObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/cancel"]["post"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/RunObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs"]["post"]
            ["requestBody"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/SubmitToolOutputsRunRequest"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs"]["post"]
            ["responses"]["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/RunObject"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/steps"]["get"]["responses"]["200"]
            ["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/ListRunStepsResponse"
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/steps/{step_id}"]["get"]["responses"]
            ["200"]["content"]["application/json"]["schema"]["$ref"],
        "#/components/schemas/RunStepObject"
    );
    assert_eq!(
        json["paths"]["/market/products"]["get"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/market/offers"]["get"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/market/quotes"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/validate"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/reserve"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/confirm"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/marketing/coupons/rollback"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/commercial/account"]["get"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/commercial/account/benefit-lots"]["get"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["components"]["schemas"]["GatewayCommercialBenefitLotsResponse"]["properties"]["page"]
            ["$ref"],
        "#/components/schemas/GatewayCommercialBenefitLotPage"
    );
    assert_eq!(
        json["paths"]["/v1/chat/completions"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/responses/input_tokens"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/responses/compact"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/responses/{response_id}/cancel"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/conversations"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/conversations/{conversation_id}/items"]["post"]["security"][0]
            ["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/completions"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/audio/transcriptions"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/images/generations"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/assistants"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/realtime/sessions"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/audio/speech"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/files"]["get"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/files"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/uploads"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/batches"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/vector_stores/{vector_store_id}/search"]["post"]["security"][0]
            ["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/threads"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/messages"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/threads/runs"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs"]["post"]
            ["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1/messages"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );
    assert_eq!(
        json["paths"]["/v1beta/models/{tail}"]["post"]["security"][0]["bearerAuth"],
        serde_json::json!([])
    );

    let docs = app
        .oneshot(Request::builder().uri("/docs").body(Body::empty()).unwrap())
        .await
        .unwrap();

    assert_eq!(docs.status(), StatusCode::OK);
    let bytes = to_bytes(docs.into_body(), usize::MAX).await.unwrap();
    let html = String::from_utf8(bytes.to_vec()).unwrap();
    assert!(html.contains("SDKWORK Gateway API"));
    assert!(html.contains("/openapi.json"));
}

#[test]
fn try_gateway_router_returns_error_for_invalid_http_exposure_env() {
    let _lock = http_exposure_env_lock().lock().unwrap();
    let key = "SDKWORK_BROWSER_ALLOWED_ORIGINS";
    let previous = std::env::var(key).ok();
    std::env::set_var(key, ";;;");

    let result = sdkwork_api_interface_http::try_gateway_router();

    match previous {
        Some(value) => std::env::set_var(key, value),
        None => std::env::remove_var(key),
    }

    let error = result.expect_err("invalid env should return an error");
    assert!(error
        .to_string()
        .contains("invalid list value for SDKWORK_BROWSER_ALLOWED_ORIGINS"));
}

#[tokio::test]
async fn try_gateway_router_with_pool_returns_error_for_invalid_http_exposure_env() {
    let _lock = http_exposure_env_lock().lock().unwrap();
    let key = "SDKWORK_BROWSER_ALLOWED_ORIGINS";
    let previous = std::env::var(key).ok();
    std::env::set_var(key, ";;;");
    let pool = sdkwork_api_storage_sqlite::run_migrations("sqlite::memory:")
        .await
        .unwrap();

    let result = sdkwork_api_interface_http::try_gateway_router_with_pool(pool);

    match previous {
        Some(value) => std::env::set_var(key, value),
        None => std::env::remove_var(key),
    }

    let error = result.expect_err("invalid env should return an error");
    assert!(error
        .to_string()
        .contains("invalid list value for SDKWORK_BROWSER_ALLOWED_ORIGINS"));
}
