import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const appRoot = path.resolve(import.meta.dirname, '..');

function read(relativePath) {
  return readFileSync(path.join(appRoot, relativePath), 'utf8');
}

test('portal billing surfaces structured payment methods and outcome evidence', () => {
  const billingPage = read('packages/sdkwork-router-portal-billing/src/pages/index.tsx');
  const portalTypes = read('packages/sdkwork-router-portal-types/src/index.ts');
  const zhMessages = read('packages/sdkwork-router-portal-commons/src/portalMessages.zh-CN.ts');

  assert.match(portalTypes, /export type PortalCommercePaymentProvider =/);
  assert.match(portalTypes, /'stripe'/);
  assert.match(portalTypes, /'alipay'/);
  assert.match(portalTypes, /'wechat_pay'/);
  assert.match(portalTypes, /export type PortalCommerceCheckoutMethodChannel =/);
  assert.match(portalTypes, /export type PortalCommerceCheckoutMethodSessionKind =/);
  assert.match(portalTypes, /'operator_action'/);
  assert.match(portalTypes, /'hosted_checkout'/);
  assert.match(portalTypes, /'qr_code'/);
  assert.match(portalTypes, /supports_webhook: boolean;/);
  assert.match(portalTypes, /recommended: boolean;/);
  assert.match(portalTypes, /session_kind: PortalCommerceCheckoutMethodSessionKind;/);
  assert.match(portalTypes, /session_reference: string;/);
  assert.match(portalTypes, /qr_code_payload\?: string \| null;/);
  assert.match(portalTypes, /webhook_verification: string;/);
  assert.match(portalTypes, /supports_refund: boolean;/);
  assert.match(portalTypes, /supports_partial_refund: boolean;/);
  assert.match(portalTypes, /checkout_method_id\?: string \| null;/);

  assert.match(billingPage, /function checkoutMethodProviderLabel\(/);
  assert.match(billingPage, /function checkoutMethodChannelLabel\(/);
  assert.match(billingPage, /function checkoutMethodSessionKindLabel\(/);
  assert.match(billingPage, /function buildProviderEventReplayId\(/);
  assert.match(billingPage, /function preferredProviderCallbackMethod\(/);
  assert.match(billingPage, /providerCallbackMethodId/);
  assert.match(billingPage, /provider:\s*method\.provider/);
  assert.match(billingPage, /provider_event_id:\s*buildProviderEventReplayId\(/);
  assert.match(billingPage, /checkout_method_id:\s*method\.id/);
  assert.match(billingPage, /method\.session_reference/);
  assert.match(billingPage, /method\.webhook_verification/);
  assert.match(billingPage, /method\.supports_refund/);
  assert.match(billingPage, /method\.supports_partial_refund/);
  assert.match(billingPage, /method\.qr_code_payload/);
  assert.match(billingPage, /Checkout reference/);
  assert.match(billingPage, /Verification method/);
  assert.match(billingPage, /Payment outcome sandbox/);
  assert.match(billingPage, /Sandbox method/);
  assert.match(billingPage, /Manual confirmation/);
  assert.match(billingPage, /Signed callback check/);
  assert.match(billingPage, /Stripe signature check/);
  assert.match(billingPage, /Alipay RSA-SHA256 check/);
  assert.match(billingPage, /WeChat Pay RSA-SHA256 check/);
  assert.match(billingPage, /Refund coverage/);
  assert.match(billingPage, /Partial refunds/);
  assert.match(billingPage, /QR code content/);
  assert.match(billingPage, /Hosted checkout flow/);
  assert.match(billingPage, /QR checkout flow/);
  assert.match(billingPage, /Manual step/);
  assert.match(billingPage, /Checkout details/);
  assert.match(billingPage, /Open checkout/);
  assert.match(billingPage, /This checkout is already closed, so there are no remaining payment actions\./);
  assert.match(billingPage, /Payment outcomes/);
  assert.match(billingPage, /Apply settlement, failure, or cancellation outcomes for the selected payment method before live payment confirmation is enabled\./);
  assert.match(billingPage, /Stripe/);
  assert.match(billingPage, /Alipay/);
  assert.match(billingPage, /WeChat Pay/);
  assert.match(billingPage, /Hosted checkout/);
  assert.match(billingPage, /Scan QR/);
  assert.doesNotMatch(billingPage, /Operator action/);
  assert.doesNotMatch(billingPage, /Webhook verification/);
  assert.doesNotMatch(billingPage, /\bWebhook\b/);
  assert.doesNotMatch(billingPage, /Checkout session/);
  assert.doesNotMatch(billingPage, /Open session/);
  assert.doesNotMatch(billingPage, /Loading session/);
  assert.doesNotMatch(billingPage, /Loading checkout session/);
  assert.doesNotMatch(billingPage, /existing provider session/);
  assert.doesNotMatch(billingPage, /Manual action/);
  assert.doesNotMatch(billingPage, /Hosted checkout session/);
  assert.doesNotMatch(billingPage, /QR code session/);
  assert.doesNotMatch(billingPage, /This checkout session is already closed, so there are no remaining payment actions\./);
  assert.doesNotMatch(billingPage, /Session reference/);
  assert.doesNotMatch(billingPage, /QR payload/);
  assert.doesNotMatch(billingPage, /Refund support/);
  assert.doesNotMatch(billingPage, /\bPartial refund\b/);
  assert.match(zhMessages, /'Manual lab':/);
  assert.match(zhMessages, /'WeChat Pay':/);
  assert.match(zhMessages, /'Hosted checkout':/);
  assert.match(zhMessages, /'Scan QR':/);
  assert.match(zhMessages, /'Checkout reference':/);
  assert.match(zhMessages, /'Verification method':/);
  assert.match(zhMessages, /'Payment outcome sandbox':/);
  assert.match(zhMessages, /'Sandbox method':/);
  assert.match(zhMessages, /'Manual confirmation':/);
  assert.match(zhMessages, /'Signed callback check':/);
  assert.match(zhMessages, /'Stripe signature check':/);
  assert.match(zhMessages, /'Alipay RSA-SHA256 check':/);
  assert.match(zhMessages, /'WeChat Pay RSA-SHA256 check':/);
  assert.match(zhMessages, /'Refund coverage':/);
  assert.match(zhMessages, /'Partial refunds':/);
  assert.match(zhMessages, /'QR code content':/);
  assert.match(zhMessages, /'Hosted checkout flow':/);
  assert.match(zhMessages, /'QR checkout flow':/);
  assert.match(zhMessages, /'Manual step':/);
  assert.match(zhMessages, /'Checkout details':/);
  assert.match(zhMessages, /'Open checkout':/);
  assert.match(zhMessages, /'Payment outcomes':/);
  assert.doesNotMatch(zhMessages, /'Operator action':/);
  assert.doesNotMatch(zhMessages, /'Webhook verification':/);
  assert.doesNotMatch(zhMessages, /Webhook:/);
  assert.doesNotMatch(zhMessages, /'Checkout session':/);
  assert.doesNotMatch(zhMessages, /'Open session':/);
  assert.doesNotMatch(zhMessages, /'Loading session\.\.\.':/);
  assert.doesNotMatch(zhMessages, /'Loading checkout session for \{orderId\}\.\.\.':/);
  assert.doesNotMatch(zhMessages, /existing provider session/);
  assert.doesNotMatch(zhMessages, /'Manual action':/);
  assert.doesNotMatch(zhMessages, /'Hosted checkout session':/);
  assert.doesNotMatch(zhMessages, /'QR code session':/);
  assert.doesNotMatch(zhMessages, /'Session reference':/);
  assert.doesNotMatch(zhMessages, /'QR payload':/);
  assert.doesNotMatch(zhMessages, /'Refund support':/);
  assert.doesNotMatch(zhMessages, /'Partial refund':/);
});
