import { clsx, type ClassValue } from 'clsx';
import {
  createElement,
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react';
import { twMerge } from 'tailwind-merge';

import { setActivePortalFormatLocale } from './format-core';
import {
  preloadPortalCoreLocale,
  setActivePortalCoreLocale,
  translatePortalText as translatePortalCoreText,
  translatePortalTextForLocale,
} from './i18n-core';

export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}

export type PortalLocale = 'en-US' | 'zh-CN';

type TranslationValues = Record<string, string | number>;

type PortalI18nContextValue = {
  locale: PortalLocale;
  setLocale: (locale: PortalLocale) => void;
  t: (text: string, values?: TranslationValues) => string;
};

const PORTAL_I18N_STORAGE_KEY = 'sdkwork-router-portal.locale.v1';

const PORTAL_MESSAGE_KEYS = [
  ' in {region}',
  'A one-time plaintext key will be revealed after creation.',
  'API Keys',
  'API key',
  'API key group',
  'API key details',
  'API keys',
  'Access',
  'Action required',
  'Actions',
  'Active',
  'Active posture',
  'Active preset',
  'Adaptive routing',
  'Advisory',
  'Add operator context, ownership, or rollout details for future review.',
  'Adjust the API key, time range, channel, or model filter to reveal more request facts.',
  'All API keys',
  'All channels',
  'All groups',
  'All models',
  'All offers',
  'All orders',
  'All recommended environments covered',
  'All time',
  'Already have an account?',
  'Applied routing profile',
  'Applied setup and wrote {count} file(s).',
  'Applied setup to {count} OpenClaw instance(s).',
  'Apply preset',
  'Apply setup',
  'Applying cancel...',
  'Applying failure...',
  'Applying settlement...',
  'Applying {label} setup...',
  'Applying...',
  'Archived offers',
  'Authorization header',
  'Auto',
  'Auto fallback',
  'Available',
  'Average latency',
  'Anthropic',
  'Awaiting workspace session',
  'Back to login',
  'Cancel',
  'Cancel order',
  'Canceling...',
  'Candidate assessments',
  'Candidate order remains visible so fallback posture is explainable.',
  'Candidate path',
  'Capability',
  'Channel',
  'Checkout preview',
  'Choose the portal workspace language. Shared shell copy and locale-aware formatting update immediately.',
  'Choose which workspace boundary this key should protect.',
  'Clear filters',
  'Clipboard copy is unavailable in this browser context.',
  'Close',
  'Collapse sidebar',
  'Command workbench',
  'Commerce catalog',
  'Commercial runway',
  'Continue with',
  'Copy key',
  'Copy plaintext',
  'Coupon code',
  'Coverage aligned',
  'Coverage gap',
  'Coverage gap remaining',
  'Create API key',
  'Create a password',
  'Create a standalone key without group-level routing or accounting defaults.',
  'Create a portal-managed key to reveal a one-time quickstart command for this workspace.',
  'Create account',
  'Create checkout',
  'Create your first key to connect a client or service to the SDKWork Router gateway.',
  'Created at',
  'Creating API key...',
  'Creating checkout...',
  'Credential inventory',
  'Credential inventory is synced with the latest project key state.',
  'Critical blockers and watchpoints stay visible before launch traffic expands.',
  'Custom environment',
  'Custom environment is required when the custom environment option is selected.',
  'Custom key',
  'Custom key mode requires a plaintext key before the credential can be created.',
  'Decision support',
  'Default',
  'Default provider',
  'Default provider updated locally. Save posture to publish the change.',
  'Degraded',
  'Degraded fallback',
  'Delete',
  'Deleting {label}...',
  'Deployment playbooks',
  'Desktop runtime',
  'Desktop runtime restart failed before the command center could refresh.',
  'Desktop setup',
  'Developer portal',
  'Delivery',
  'Direct gateway',
  'Disable',
  'Disabled',
  'Edit posture',
  'Edit routing posture',
  'Eligible offers',
  'Email',
  'Enable',
  'Enabled',
  'English',
  'Enter your password',
  'Export billing events CSV',
  'Environment',
  'Environment boundary',
  'Environment coverage',
  'Environment coverage aligned',
  'Environment strategy',
  'Environment: {environment}',
  'Evidence entries',
  'Examples: canary, partner, sandbox-eu',
  'Expand sidebar',
  'Expires at',
  'Expires at must be a valid date before the credential can be created.',
  'Expiring soon',
  'Failed payment',
  'Fallback reason',
  'Loading account analytics...',
  'Account analytics will appear after the portal loads billing, membership, and usage evidence.',
  'Account posture is synced with the latest billing and usage evidence.',
  'Account analytics are synced with the latest billing and usage evidence.',
  'Balance',
  'Financial account',
  'Financial account posture will appear after the portal loads billing summary and ledger evidence.',
  'Today',
  '7 days',
  'This month',
  'All',
  'Account posture',
  'Account activity',
  'Account history',
  'Recharge',
  'Total booked revenue and recent realized income stay aligned on one account surface.',
  'Call volume shows total routed demand plus recent billing windows.',
  'Billable units reflect overall account consumption and recent activity windows.',
  'Average value per request keeps account efficiency visible across billing periods.',
  'Quota headroom, membership, and booked totals stay visible in one account surface.',
  'Quota limit',
  'Available workspace balance before the quota guardrail is reached.',
  'Account activity stays searchable in one finance-ready ledger table.',
  'Switch between all activity, expenses, and revenue without leaving the same finance workbench.',
  'Adjust the search or wait for billing evidence to land.',
  'Search account history',
  'Expense',
  'Recorded',
  'Type',
  'Details',
  'Financial breakdown',
  'Billing event evidence adds capability mix, accounting mode posture, and multimodal totals to the account surface.',
  'Billing events',
  'Customer charge',
  'Capability mix',
  'Capability mix keeps the highest-charge API capabilities visible beside the account ledger.',
  'No capability mix yet',
  'Capability mix appears after billing events attribute charge across routed API capabilities.',
  'Accounting mode mix',
  'Accounting mode mix separates platform credit, BYOK, and passthrough consumption in one account slice.',
  'No accounting mode mix yet',
  'Accounting mode evidence appears after billing events record platform credit, BYOK, or passthrough traffic.',
  'Multimodal usage',
  'Images, audio, video, and music totals keep multimodal demand visible on the same financial surface.',
  'Images',
  'Audio',
  'Video',
  'Music',
  '{count} tokens',
  '{count} requests',
  '{count} images',
  '{count} audio sec',
  '{count} video sec',
  '{count} music sec',
  '{requests} requests / {events} events',
  'Recharge decision support',
  'Recharge posture combines membership baseline, accounting mode mix, and workload shape before you create a top-up order.',
  'Redeem decision support',
  'Redeem posture combines coupon runway, accounting mode mix, and workload shape before another code is applied.',
  'Redemption coverage',
  'No fulfilled coupon redemptions are recorded yet. Use the first coupon to establish a launch buffer before recharge is needed.',
  'Coupon orders have already granted {units} units across {count} fulfilled redemptions, and current demand is now better served by recharge or membership.',
  'Coupon orders have already granted {units} units across {count} fulfilled redemptions, and redeem remains a viable low-friction top-up path.',
  'Commercial highlights',
  'Commercial highlights bring accounting mode mix, top capability demand, and multimodal workload shape into the workspace overview.',
  'Leading accounting mode',
  'Leading capability',
  'Billing event evidence will appear here after routed traffic starts recording chargeback activity.',
  'Multimodal demand',
  'Multimodal demand keeps image, audio, video, and music traffic visible before another coupon is applied.',
  'Multimodal demand keeps image, audio, video, and music traffic visible before a top-up is created.',
  'Multimodal demand keeps image, audio, video, and music traffic visible inside the workspace overview.',
  'Ledger snapshot',
  'Usage record',
  'Current workspace',
  'Linked project',
  'No account history for this slice',
  'Adjust the search or switch history tabs to reveal more records.',
  'No expense history for this slice',
  'Expense history will appear once workspace usage starts generating billable activity.',
  'No revenue entries for this slice',
  'Revenue history will appear once billing ledger movements reach this account.',
  'Focus: {focus}',
  'Forgot password?',
  'Gateway key mode',
  'Gateway posture',
  'Gateway traffic observed',
  'Guardrail posture',
  'Guardrailed',
  'Guardrails',
  'Guardrails applied',
  'Healthy',
  'Healthy baseline',
  'How to use this key',
  'Inactive',
  'Issue the first credential to start tracking environment coverage in this workspace.',
  'Issuing a Portal-managed {environment} key for this workspace...',
  'Keep the left rail aligned with claw-studio while preserving the portal route set.',
  'Keep workspace identity and shell reset controls in one place.',
  'Key label',
  'Key group',
  'Key label is required so credentials remain auditable after creation.',
  'Language',
  'Language and locale',
  'Last 24 hours',
  'Last 30 days',
  'Last 7 days',
  'Last authenticated use',
  'Latest plaintext available once',
  'Latest routing signals',
  'Launch actions',
  'Launch readiness',
  'Ledger',
  'Let Portal create a one-time plaintext secret that is stored in write-only mode.',
  'Lifecycle policy',
  'Live',
  'Live rate-limit windows were last checked {checkedAt}.',
  'Live service health was last checked {checkedAt}.',
  'Loading issued keys...',
  'Loading local instances...',
  'Loading routing profiles...',
  'Loading preview...',
  'Loading request telemetry...',
  'Loading routing posture...',
  'Loading checkout...',
  'Loading the router product command center and current launch posture...',
  'Loading...',
  'Local development uses identities from the active bootstrap profile. Email hint: {email}. Enter the matching password from your runtime configuration.',
  'Local development uses identities from the active bootstrap profile. Enter the portal email and password provisioned by your runtime configuration.',
  'Manage keys',
  'Manage groups',
  'Manage routing profiles',
  'Compiled snapshot',
  'Fallback posture',
  'Matched policy',
  'Matched policy {policyId}.',
  'Max cost',
  'Max latency',
  'Max latency ms',
  'Mode switchboard',
  'Model',
  'Move down',
  'Move up',
  'Name',
  'Name is required before this group can be saved.',
  'Name is required before this profile can be saved.',
  'Navigation',
  'Never',
  'Next boundary: {environment}',
  'Next page',
  'No API keys yet',
  'No group binding',
  'No OpenClaw instances were detected on this machine.',
  'No account?',
  'No active guardrails',
  'No candidates',
  'No accounting override',
  'No checkout methods remain',
  'No checkout selected',
  'No environment coverage yet',
  'No failed payment orders for this slice',
  'No latency sample',
  'No ledger entries for this slice',
  'No ledger entries yet',
  'No API key group scope',
  'No applied routing profile',
  'No compiled snapshots match the current filter',
  'No fallback used',
  'No matched policy',
  'No snapshot captured',
  'No routing profile override',
  'No offers for this slice',
  'No offers match the current filter.',
  'No operator notes were attached to this policy.',
  'No API key groups match the current filter.',
  'No orders for this slice',
  'No pending payment orders for this slice',
  'No points ledger entries recorded yet.',
  'No preview assessments yet',
  'No quickstart snippet yet',
  'Not recorded',
  'No routing profiles yet',
  'No routing policy matched the current preview inputs.',
  'No routing signals yet',
  'Default scope is not set.',
  'No settings found.',
  'No timeline orders for this slice',
  'No usage records for this slice',
  'Not available',
  'Not yet',
  'Notes',
  'Offer state',
  'Offers',
  'Open',
  'Open account',
  'Return to command center',
  'Open console',
  'Download App',
  'Download Center',
  'Open install guide',
  'Open quickstart',
  'Operations',
  'Open app to scan',
  'Open credits',
  'Open checkout',
  'Open the desktop app and scan this code to continue without typing credentials.',
  'OpenAI',
  'Open usage',
  'OpenClaw instances',
  'Operational focus',
  'Operator',
  'Operator-managed migration key',
  'Optional deterministic seed',
  'Optional. Leave empty to keep this key active until you revoke it.',
  'Order lane',
  'Order timeline',
  'Order workbench',
  'Ordered',
  'Over limit',
  'Page {page} of {total}',
  'Password',
  'Paste the exact plaintext value that should be stored in write-only mode.',
  'Pending',
  'Pending payment queue',
  'Open billing workbench',
  'Plaintext Api key is no longer visible on this device. Create a replacement first.',
  'Plaintext key copied to clipboard.',
  'Plaintext unavailable. Rotate this key to obtain a new one-time secret.',
  'Rotate this key to reveal a new one-time secret before applying {label} setup or copying local snippets.',
  'Platform fallback',
  'Platform credit',
  'Custom recharge is currently disabled for this workspace.',
  'Custom recharge must be at least {amount}.',
  'Custom recharge must stay below {amount}.',
  'Custom recharge must increase in steps of {amount}.',
  'BYOK',
  'Passthrough',
  'Portal endpoint',
  'Portal managed',
  'Portal operator',
  'Portal tenant',
  'Portal workspace',
  'Portal workspace settings',
  'Portal-managed key',
  'Open snapshot evidence',
  'Predictable order',
  'Preferred region',
  'Preparing account',
  'Preparing gateway command center',
  'Preparing routing workbench',
  'Preview',
  'Preview model',
  'Preview offer',
  'Preview only',
  'Preview outcome',
  'Preview redemption',
  'Preview route',
  'Preview updated with the current routing posture and added to the evidence stream.',
  'Previewing the active route...',
  'Previous page',
  'Priority #{priority}',
  'Production rollout',
  'Project rate-limit policy posture was last checked {checkedAt}.',
  'Provide an exact plaintext value when rollout coordination requires a predefined credential.',
  'QR login',
  'Quick setup',
  'Quickstart snippet',
  'Ready for first authenticated request',
  'Ready to run',
  'Recommended next',
  'Recommended next: {environment}',
  'Redeem credits',
  'Redeem now',
  'Redeeming...',
  'Refresh',
  'Refresh command center',
  'Refresh inventory',
  'Refresh preview',
  'Refresh service health',
  'Refreshing command center...',
  'Refreshing credential inventory...',
  'Refreshing service health and gateway evidence...',
  'Refreshing service health...',
  'Refreshing the full command center posture...',
  'Regional preference',
  'Review reusable routing profiles for this workspace and save the current routing posture as a reusable profile for API key groups.',
  'Revenue',
  'Registering a custom {environment} key for this workspace...',
  'Reliability guardrails',
  'Requested model',
  'Requested region',
  'Require healthy providers',
  'Inspect the compiled routing evidence for this workspace after policy, project defaults, and API key group profile overlays are combined.',
  'Reset shell preferences',
  'Restarting the embedded desktop runtime and refreshing live service posture...',
  'Restoring {label}...',
  'Review billing',
  'Revoked from gateway traffic',
  'Revoking {label}...',
  'Rotation checklist',
  'Routing',
  'Routing profiles',
  'Routing profile',
  'Routing posture',
  'Routing profile label',
  'Grouped keys',
  'Ungrouped keys',
  'Save group',
  'Save as profile',
  'Save current posture',
  'Routing workbench',
  'Run a preview or wait for live traffic to collect routing signals.',
  'Run a preview to inspect provider-level candidate assessments.',
  'Run preview',
  'Running preview...',
  'Runtime modes',
  'SDKWork Router',
  'SDKWork Router Desktop',
  'SLO posture',
  'Save posture',
  'Saving routing preferences for this project...',
  'Saving...',
  'Search compiled snapshots',
  'Search API keys',
  'Search groups',
  'Search routing profiles',
  'Download',
  'Docs',
  'Console',
  'Home',
  'Top navigation',
  'Software Downloads',
  'Software Downloads focuses on installation targets, runtime requirements, and guided onboarding.',
  'Software Downloads should drive users toward a successful first launch instead of acting like a dead asset index.',
  'Gateway Service Bundle',
  'Best for local gateway runtime, desktop orchestration, and quick QR-based sign in.',
  'Optimized for Apple Silicon and operator-facing desktop management.',
  'Run the router as a service and pair it with the portal console and public docs.',
  'Background service',
  'System requirements',
  'The selected docs group stays in the URL so operators can reopen the same guide with one shared link.',
  'Start the local product with the embedded portal shell and runtime evidence.',
  'Keep the desktop runtime available in the background for local routing.',
  'Host the full router product for remote teams and shared gateway traffic.',
  'Move from install guidance into a real product session without switching visual systems.',
  'Review the minimum runtime expectations before distributing portal software to operators or teams.',
  'Node.js 20+ for local tooling and workspace automation tasks.',
  'Desktop runtime access for QR sign-in, local health checks, and product orchestration.',
  'Gateway service connectivity so the console and software downloads flow point at the same runtime boundary.',
  'Installation steps',
  'Step {index}',
  'Download the desktop or service artifact that matches your environment.',
  'Launch the runtime, sign in, and verify gateway health before creating workspace credentials.',
  'Use the console and docs center to finish provider routing, API key setup, and usage governance.',
  'Use as posture',
  'Showing {start}-{end} of {total} keys',
  'Showing {start}-{end} of {total} records',
  'Showing {visible} of {total} keys',
  'Search gateway evidence',
  'Search ledger',
  'Search offers or ledger',
  'Search order lifecycle',
  'Search routing evidence',
  'Search settings...',
  'Select at least one OpenClaw instance before applying setup.',
  'Selected provider',
  'Selection evidence is available from the current routing trace.',
  'Selection evidence is linked to the compiled route state when a snapshot id is available.',
  'Selection reason',
  'Selection seed',
  'Slug',
  'Set default',
  'Settings',
  'Settle order',
  'Settling...',
  'Show or hide workspace modules while keeping the left rail compact and stable.',
  'Sidebar behavior',
  'Sign out',
  'Simplified Chinese',
  'Manual lab',
  'Stripe',
  'Alipay',
  'WeChat Pay',
  'Hosted checkout',
  'Hosted checkout flow',
  'Manual step',
  'QR checkout flow',
  'Scan QR',
  'Sandbox method',
  'Choose sandbox method',
  'Checkout flow',
  'Checkout details',
  'Checkout reference',
  'Verification method',
  'Manual confirmation',
  'Signed callback check',
  'Stripe signature check',
  'Alipay RSA-SHA256 check',
  'WeChat Pay RSA-SHA256 check',
  'Refund coverage',
  'Partial refunds',
  'QR code content',
  'Payment outcomes',
  'Recommended',
  'Refunded',
  'Settlement coverage',
  'Settlement coverage keeps benefit lots, credit holds, and request capture aligned in one billing snapshot.',
  'Payment outcome sandbox',
  'Apply settlement, failure, or cancellation outcomes for the selected payment method before live payment confirmation is enabled.',
  'Sandbox only',
  '{provider} / {channel}',
  'Payment outcomes will use {provider} on {channel}.',
  'Applying {provider} settlement outcome for {orderId}...',
  'Applying {provider} failure outcome for {orderId}...',
  'Applying {provider} cancellation outcome for {orderId}...',
  '{targetName} was settled after the {provider} payment confirmation.',
  '{targetName} was marked failed after the {provider} payment confirmation.',
  '{targetName} was canceled after the {provider} payment confirmation.',
  'Apply cancellation outcome',
  'Apply failure outcome',
  'Apply settlement outcome',
  'Source',
  'Staging',
  'Started {checkedAt}',
  'Status',
  'Strategy',
  'Color',
  'Current posture',
  'Description',
  'Create a reusable routing profile from the current project posture without opening the admin control plane.',
  'Keep the new profile immediately selectable by API key groups after creation.',
  'Default scope',
  'Accounting mode',
  'Subject',
  'System',
  'System generated',
  'Test',
  'The command center could not load the current gateway posture.',
  'The command center could not refresh the current gateway posture.',
  'The command center is showing the latest compatibility, runtime, and commercial posture.',
  'The current preview explains why the selected provider won the route.',
  'The current routing strategy, provider order, and guardrails will be captured into a reusable profile for this workspace.',
  'The preview did not expose additional assessment detail for this provider.',
  'The provider chosen by the latest routing preview.',
  'Fallback reasoning stays visible so you can distinguish degraded routing from the preferred routing path.',
  'Theme color',
  'Theme color updates the accent surfaces without changing the claw-style shell contract.',
  'Theme mode',
  'Theme mode stays synchronized across header, sidebar, content surfaces, and dialogs.',
  'This credential expires on {date}.',
  'This credential has no expiry. Keep revocation ownership explicit.',
  'Time range',
  'Top-ranked eligible provider',
  'Topology playbooks',
  'Total requests',
  'Total spend',
  'Total tokens',
  'Traffic distribution',
  'Translated routes',
  'Unavailable',
  'Unknown',
  'Unknown capability',
  'Unknown provider',
  'Unknown source',
  'Unreachable',
  'Ungrouped',
  'Updated {checkedAt}',
  'Usage',
  'Usage cards and ledger-grade request facts reflect the current filtered workspace slice.',
  'Usage records',
  'Usage method',
  'Validate with a key',
  'View compiled snapshots',
  'View details',
  'View mode',
  'Bind this key to a reusable workspace group for shared routing, accounting, and rollout defaults.',
  'View every group-backed and standalone key in this workspace.',
  'Show keys that do not inherit a reusable group posture.',
  'Routing profile {profileId}',
  '{groupName} ({environment})',
  'API key groups',
  'Create group',
  'Delete group',
  'Enable group',
  'Disable group',
  'Delete this group from the workspace?',
  'Group created. Review the refreshed policy inventory.',
  'Group updated. Review the refreshed policy inventory.',
  'Group enabled. Keys in this workspace can bind to it again.',
  'Group disabled. New key assignments now require a different group.',
  'Group deleted. Review the refreshed policy inventory.',
  'Failed to save API key group.',
  'Failed to save routing profile.',
  'Loading compiled snapshots...',
  'Compiled snapshots',
  'Bound API key group',
  'Broaden the query or refresh the workspace after new routing decisions land.',
  'Failed to update API key group status.',
  'Failed to delete API key group.',
  'Manage reusable defaults for environment-scoped keys, routing profile overrides, and accounting posture inside this workspace.',
  'Create the first reusable group to share routing and accounting defaults across keys.',
  'Profile loaded into the current routing posture. Save posture when you are ready to publish it.',
  'Routing profile saved. API key groups can now bind to it.',
  'Save the current routing posture as a reusable profile, then bind it to API key groups.',
  'Group governance',
  'API key groups tie credential issuance, routing profile defaults, and chargeback accountability into one workspace view.',
  'Leading chargeback group',
  'Default accounting mode',
  'This is the most common accounting override across active API key groups.',
  'No active API key group currently overrides accounting mode.',
  'Grouping posture',
  '{grouped} grouped keys / {ungrouped} ungrouped keys keep chargeback scope visible before traffic scales.',
  'WELCOME100',
  'Within limit',
  'Workbench lane',
  'Workspace',
  'Workspace owner',
  'Workspace posture',
  'Workspace preferences',
  'Write-only',
  'name@example.com',
  'project-wide',
  '{count} key(s) visible',
  '{count} signals',
  '{label} has been revoked and will no longer authenticate requests.',
  '{label} is active again and can authenticate gateway traffic.',
  '{label} was deleted from this workspace.',
  '{source} used {strategy}{regionSuffix}.',
  '{visible} of {total} keys visible',
  '{visible} of {total} rows visible',
  '{windowSeconds}s window ends {endsAt}',
  'Audio transcription',
  'Chat completions',
  'Control plane simulation',
  'Cost {cost}',
  'HTTP {httpStatus} · {latency}',
  'Embeddings',
  'Example: 0.30 USD ceiling',
  'Example: 250 ms target',
  'Example: Balanced production posture',
  'Example: Chat completions',
  'Image generation',
  'Latency {latency}',
  'Live traffic',
  'Music generation',
  'Multimodal reasoning',
  'No HTTP status',
  'No sample',
  'Preview request',
  'Rank {rank}',
  'Responses',
  'Unhealthy',
  'API key {keyHash}',
  'Route {routeKey}',
  'Model {modelName}',
  '{limitRequests} req / {windowSeconds}s · burst {burstRequests}',
  '{requestCount} / {limitRequests} requests · {remainingRequests} remaining',
  'Awaiting pending order',
  'Canceled',
  'Closed',
  'Compatibility routes',
  'Coupon',
  'Current status',
  'Checkout workbench keeps checkout access, selected reference, and payable price aligned under one payment method.',
  'Manual settlement',
  'No checkout guidance is available for this order yet.',
  'Primary method',
  '{targetName} was queued in Pending payment queue. Open the checkout workbench to complete payment before quota or membership changes are applied.',
  'Creating a checkout order for {targetId}...',
  'Created',
  'Failed',
  'Fulfilled',
  'Granted units',
  'Bonus units',
  'Kind',
  'Opening checkout...',
  'Loading checkout for {orderId}...',
  'Loading live checkout pricing for {targetId}...',
  'None',
  'Not required',
  'Offer',
  'Open checkout link',
  'Opening {provider} checkout for {targetName}...',
  'Reopening {provider} checkout for {targetName}...',
  'Ordered providers keep deterministic failover readable for operators and support teams.',
  'Payable',
  'Payment pending',
  'Payment method',
  'Planned',
  'Checkout access',
  'Billing view keeps live quota, checkout progress, and payment history in one place.',
  '{reference} is the current {provider} / {channel} payment reference for this order.',
  '{reference} is the current checkout reference for this order.',
  'Recharge pack',
  'Applying provider cancellation outcome for {orderId}...',
  'Applying provider failure outcome for {orderId}...',
  'Applying provider settlement outcome for {orderId}...',
  'Service health',
  'Settled',
  'Settling {targetName} into active workspace quota...',
  'Subscription plan',
  'Verification commands',
  '{kind} / {price}',
  '{planName} is the active workspace membership and defines the current subscription entitlement baseline.',
  '{targetName} created a {provider} checkout attempt, but no checkout link was returned.',
  '{targetName} is priced by the live commerce quote service and ready to create as a pending payment order.',
  '{targetName} now uses the {provider} checkout launch path.',
  '{targetName} was canceled and left out of quota fulfillment.',
  '{targetName} was canceled after provider payment confirmation.',
  '{targetName} was marked failed and left out of fulfillment.',
  '{targetName} was queued in Pending payment queue. Settle it before quota or membership changes are applied.',
  '{targetName} was settled and moved into Order timeline.',
  '{targetName} was settled after provider payment confirmation.',
  'Canceling {targetName} before fulfillment is applied...',
  'Start checkout',
  'Resume checkout',
  'Retry with new attempt',
  'No active membership is recorded yet. Complete a subscription checkout to activate monthly entitlement posture.',
  'Pending payment queue keeps unpaid or unfulfilled orders visible until payment completes or the order leaves the queue.',
  'Failed payment keeps checkout attempts that need coupon updates, a different payment method, or a fresh checkout visible for follow-up.',
  'Commercial account keeps balance, holds, and account identity visible beside the workspace billing posture.',
  'Payment history keeps checkout outcomes, payment method evidence, and refund status visible in one billing timeline.',
  'Refund history keeps completed refund outcomes, payment method evidence, and the resulting order status visible without reopening each order.',
  'Payment update reference',
  'Open the checkout workbench from Pending payment queue to inspect the selected payment method.',
  'Open the checkout workbench from Pending payment queue to inspect the selected order.',
  'Starting {provider} checkout for {targetName}...',
  'Creating a fresh {provider} checkout attempt for {targetName}...',
  'Past due',
  'Paused',
  'Provider',
  'Grace period',
  'Enterprise quota',
  'Redeem',
  'Growth',
  'Open redeem',
  'Coupons, invites, and activation rewards',
  'Cash balance, history visibility, and payment posture',
  'Loading redeem workspace...',
  'Redeem code',
  'Redeem history',
  'Reward history',
  'Invite rewards',
  'Redeem history is synced with the latest workspace posture.',
  '{redeemed} redeemed / {rolledBack} rolled back.',
  'Redeem the current workspace with one valid coupon code.',
  'Copy the workspace invite code or direct link to share rewards.',
  'Enter coupon code',
  'Redeeming {code} for this workspace...',
  'Unlimited',
  'Redeem offers and invite rewards are synced with the latest workspace posture.',
  'Redeem workspace offers and keep activation rewards visible before the next growth push.',
  '{code} was redeemed and the workspace balance was refreshed.',
  'Coupon code not recognized in the current workspace catalog.',
  'No redemption history yet',
  'No coupon redemptions have been applied to this workspace yet.',
  'No reward history yet',
  'Confirmed coupon rewards and rollbacks will appear here after the first successful marketing redemption closes the loop.',
  'Pending invites',
  'Rewarded activations',
  'Search redeem offers',
  'Invite teammates',
  'Copy invite link',
  'Copy invite code',
  'Invite code',
  'Invite link',
  'Invite code copied to clipboard.',
  'Invite link copied to clipboard.',
  'Invites that have been sent but have not yet activated and earned a reward.',
  'Activated invitations that already converted into reward units.',
  'Invite teammates with one code path and track which activations have already earned rewards.',
  'Reward cadence',
  'Keep invite ownership, target audience, and activation reward timing visible in one place.',
  'Audience',
  'Reward policy',
  'Reward units land after activation and stay visible inside account history.',
  'Search invite history',
  'Reward status',
  'Pending reward',
  'Rewarded',
  'Invited workspace',
  'Contact',
  'Sent',
  'Activation',
  'Activated {date}',
  'Waiting for activation',
  'Reward',
  'No invites for this slice',
  'Adjust the invite search or reward status to reveal a different activation record.',
  'Share one short code for operator onboarding, billing activation, and reward tracking.',
  'The link opens the same redeem path with workspace context prefilled for faster activation.',
  'Operators, finance owners, and new workspace activations',
  'Core identity, workspace ownership, and recovery posture stay visible before you change settings.',
  '{benefitType} #{lotId}',
  'Checkout attempts',
  'Latest attempt',
  'Attempt #{sequence}',
  'Succeeded',
  'Expired',
  'Partially refunded',
  'Initiated',
  'Updated',
  'No checkout attempts recorded yet',
  'No checkout attempts have been recorded for this order yet.',
  'Checkout attempts keep checkout access, retries, and checkout references visible inside the same workbench.',
  'Checkout attempts that closed on the failure path and need a fresh checkout decision.',
  'The latest {provider} checkout can still be resumed, so the workbench will reopen the existing checkout.',
  'The latest {provider} attempt no longer has a reusable checkout link, so the workbench will create a fresh checkout attempt.',
  'No {provider} checkout attempt exists yet for this order. Start the first checkout now.',
  'This checkout is already closed, so there are no remaining payment actions.',
  '{count} billing events retained an applied profile id.',
  '{count} billing events retained a compiled snapshot id.',
] as const;

export const PORTAL_LOCALE_OPTIONS: Array<{ id: PortalLocale; labelKey: string }> = [
  { id: 'en-US', labelKey: 'English' },
  { id: 'zh-CN', labelKey: 'Simplified Chinese' },
];

let activePortalLocale: PortalLocale = 'en-US';

function normalizeLocale(value: string | null | undefined): PortalLocale {
  if (!value) {
    return 'en-US';
  }

  return value.toLowerCase().startsWith('zh') ? 'zh-CN' : 'en-US';
}

export async function preloadPortalLocale(locale: PortalLocale): Promise<void> {
  await preloadPortalCoreLocale(locale);
}

function resolveInitialLocale(): PortalLocale {
  if (typeof window === 'undefined') {
    return activePortalLocale;
  }

  let locale: PortalLocale;

  try {
    const persisted = window.localStorage.getItem(PORTAL_I18N_STORAGE_KEY);
    if (persisted) {
      locale = normalizeLocale(persisted);
    } else {
      locale = normalizeLocale(window.navigator.language);
    }
  } catch {
    // Ignore storage access failures and fall back to browser locale.
    locale = normalizeLocale(window.navigator.language);
  }

  activePortalLocale = locale;
  setActivePortalCoreLocale(locale);
  setActivePortalFormatLocale(locale);
  return locale;
}

const PortalI18nContext = createContext<PortalI18nContextValue | null>(null);

export async function preloadPreferredPortalLocale(): Promise<void> {
  await preloadPortalLocale(resolveInitialLocale());
}

export function translatePortalText(text: string, values?: TranslationValues): string {
  return translatePortalCoreText(text, values);
}

export function PortalI18nProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<PortalLocale>(resolveInitialLocale);
  const [translationRevision, setTranslationRevision] = useState(0);

  activePortalLocale = locale;
  setActivePortalCoreLocale(locale);
  setActivePortalFormatLocale(locale);

  useEffect(() => {
    if (locale !== 'zh-CN') {
      return undefined;
    }

    let cancelled = false;

    void preloadPortalLocale(locale).then(() => {
      if (!cancelled) {
        setTranslationRevision((current) => current + 1);
      }
    });

    return () => {
      cancelled = true;
    };
  }, [locale]);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      try {
        window.localStorage.setItem(PORTAL_I18N_STORAGE_KEY, locale);
      } catch {
        // Ignore storage write failures.
      }
    }

    if (typeof document !== 'undefined') {
      document.documentElement.lang = locale;
    }
  }, [locale]);

  const value = useMemo<PortalI18nContextValue>(
    () => ({
      locale,
      setLocale,
      t: (text, values) => translatePortalTextForLocale(locale, text, values),
    }),
    [locale, translationRevision],
  );

  return createElement(PortalI18nContext.Provider, { key: locale, value }, children);
}

export function usePortalI18n(): PortalI18nContextValue {
  const context = useContext(PortalI18nContext);

  if (!context) {
    throw new Error('Portal i18n hooks must be used inside PortalI18nProvider.');
  }

  return context;
}

export { copyText } from './clipboard';
export { formatCurrency, formatDateTime, formatUnits } from './format-core';
