use super::*;

pub(super) fn register_billing_routes(router: Router<AdminApiState>) -> Router<AdminApiState> {
    router
        .route(
            "/admin/usage/records",
            get(billing::list_usage_records_handler),
        )
        .route("/admin/usage/summary", get(billing::usage_summary_handler))
        .route(
            "/admin/billing/events",
            get(billing::list_billing_events_handler),
        )
        .route(
            "/admin/billing/events/summary",
            get(billing::billing_events_summary_handler),
        )
        .route(
            "/admin/billing/ledger",
            get(billing::list_ledger_entries_handler),
        )
        .route(
            "/admin/billing/summary",
            get(billing::billing_summary_handler),
        )
        .route(
            "/admin/billing/accounts",
            get(billing::list_canonical_accounts_handler),
        )
        .route(
            "/admin/billing/accounts/{account_id}/balance",
            get(billing::get_canonical_account_balance_handler),
        )
        .route(
            "/admin/billing/accounts/{account_id}/benefit-lots",
            get(billing::list_canonical_account_benefit_lots_handler),
        )
        .route(
            "/admin/billing/accounts/{account_id}/ledger",
            get(billing::list_canonical_account_ledger_handler),
        )
        .route(
            "/admin/billing/account-holds",
            get(billing::list_canonical_account_holds_handler),
        )
        .route(
            "/admin/billing/request-settlements",
            get(billing::list_canonical_request_settlements_handler),
        )
        .route(
            "/admin/billing/pricing-lifecycle/synchronize",
            post(pricing::synchronize_canonical_pricing_lifecycle_handler),
        )
        .route(
            "/admin/billing/pricing-plans",
            get(pricing::list_canonical_pricing_plans_handler)
                .post(pricing::create_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}",
            put(pricing::update_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/clone",
            post(pricing::clone_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/schedule",
            post(pricing::schedule_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/publish",
            post(pricing::publish_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-plans/{pricing_plan_id}/retire",
            post(pricing::retire_canonical_pricing_plan_handler),
        )
        .route(
            "/admin/billing/pricing-rates",
            get(pricing::list_canonical_pricing_rates_handler)
                .post(pricing::create_canonical_pricing_rate_handler),
        )
        .route(
            "/admin/billing/pricing-rates/{pricing_rate_id}",
            put(pricing::update_canonical_pricing_rate_handler),
        )
        .route(
            "/admin/billing/quota-policies",
            get(pricing::list_quota_policies_handler).post(pricing::create_quota_policy_handler),
        )
        .route(
            "/admin/payments/orders",
            get(payments::list_payment_orders_handler),
        )
        .route(
            "/admin/payments/orders/{payment_order_id}",
            get(payments::get_payment_order_dossier_handler),
        )
        .route(
            "/admin/payments/refunds",
            get(payments::list_refund_orders_handler),
        )
        .route(
            "/admin/payments/refunds/{refund_order_id}/approve",
            post(payments::approve_refund_order_handler),
        )
        .route(
            "/admin/payments/refunds/{refund_order_id}/cancel",
            post(payments::cancel_refund_order_handler),
        )
        .route(
            "/admin/payments/refunds/{refund_order_id}/start",
            post(payments::start_refund_order_handler),
        )
        .route(
            "/admin/payments/gateway-accounts",
            get(payments::list_payment_gateway_accounts_handler)
                .post(payments::upsert_payment_gateway_account_handler),
        )
        .route(
            "/admin/payments/channel-policies",
            get(payments::list_payment_channel_policies_handler)
                .post(payments::upsert_payment_channel_policy_handler),
        )
        .route(
            "/admin/payments/reconciliation-lines",
            get(payments::list_payment_reconciliation_lines_handler),
        )
        .route(
            "/admin/payments/reconciliation-lines/{reconciliation_line_id}/resolve",
            post(payments::resolve_payment_reconciliation_line_handler),
        )
        .route(
            "/admin/payments/reconciliation-summary",
            get(payments::payment_reconciliation_summary_handler),
        )
}
