use super::*;

pub(super) fn register_catalog_routes(router: Router<AdminApiState>) -> Router<AdminApiState> {
    router
        .route(
            "/admin/tenants/{tenant_id}/providers/readiness",
            get(catalog::list_tenant_provider_readiness_handler),
        )
        .route(
            "/admin/channels",
            get(catalog::list_channels_handler).post(catalog::create_channel_handler),
        )
        .route(
            "/admin/channels/{channel_id}",
            delete(catalog::delete_channel_handler),
        )
        .route(
            "/admin/providers",
            get(catalog::list_providers_handler).post(catalog::create_provider_handler),
        )
        .route(
            "/admin/providers/official-configs",
            get(catalog::list_official_provider_configs_handler)
                .post(catalog::upsert_official_provider_config_handler),
        )
        .route(
            "/admin/providers/{provider_id}",
            delete(catalog::delete_provider_handler),
        )
        .route(
            "/admin/credentials",
            get(catalog::list_credentials_handler).post(catalog::create_credential_handler),
        )
        .route(
            "/admin/credentials/{tenant_id}/providers/{provider_id}/keys/{key_reference}",
            delete(catalog::delete_credential_handler),
        )
        .route(
            "/admin/channel-models",
            get(catalog::list_channel_models_handler).post(catalog::create_channel_model_handler),
        )
        .route(
            "/admin/channel-models/{channel_id}/models/{model_id}",
            delete(catalog::delete_channel_model_handler),
        )
        .route(
            "/admin/provider-accounts",
            get(catalog::list_provider_accounts_handler)
                .post(catalog::create_provider_account_handler),
        )
        .route(
            "/admin/provider-accounts/{provider_account_id}",
            delete(catalog::delete_provider_account_handler),
        )
        .route(
            "/admin/provider-models",
            get(catalog::list_provider_models_handler).post(catalog::create_provider_model_handler),
        )
        .route(
            "/admin/provider-models/{proxy_provider_id}/channels/{channel_id}/models/{model_id}",
            delete(catalog::delete_provider_model_handler),
        )
        .route(
            "/admin/models",
            get(catalog::list_models_handler).post(catalog::create_model_handler),
        )
        .route(
            "/admin/models/{external_name}/providers/{provider_id}",
            delete(catalog::delete_model_handler),
        )
        .route(
            "/admin/model-prices",
            get(catalog::list_model_prices_handler).post(catalog::create_model_price_handler),
        )
        .route(
            "/admin/model-prices/{channel_id}/models/{model_id}/providers/{proxy_provider_id}",
            delete(catalog::delete_model_price_handler),
        )
}
