use super::*;

pub(super) fn register_commerce_routes(router: Router<AdminApiState>) -> Router<AdminApiState> {
    router
        .route(
            "/admin/commerce/orders",
            get(commerce::list_recent_commerce_orders_handler),
        )
        .route(
            "/admin/commerce/catalog-publications",
            get(commerce::list_commercial_catalog_publications_handler),
        )
        .route(
            "/admin/commerce/catalog-publications/{publication_id}",
            get(commerce::get_commercial_catalog_publication_handler),
        )
        .route(
            "/admin/commerce/catalog-publications/{publication_id}/publish",
            post(commerce::publish_commercial_catalog_publication_handler),
        )
        .route(
            "/admin/commerce/catalog-publications/{publication_id}/schedule",
            post(commerce::schedule_commercial_catalog_publication_handler),
        )
        .route(
            "/admin/commerce/catalog-publications/{publication_id}/retire",
            post(commerce::retire_commercial_catalog_publication_handler),
        )
        .route(
            "/admin/commerce/payment-methods",
            get(commerce::list_payment_methods_handler),
        )
        .route(
            "/admin/commerce/payment-methods/{payment_method_id}",
            put(commerce::put_payment_method_handler)
                .delete(commerce::delete_payment_method_handler),
        )
        .route(
            "/admin/commerce/payment-methods/{payment_method_id}/credential-bindings",
            get(commerce::list_payment_method_credential_bindings_handler)
                .put(commerce::replace_payment_method_credential_bindings_handler),
        )
        .route(
            "/admin/commerce/orders/{order_id}/payment-events",
            get(commerce::list_commerce_payment_events_handler),
        )
        .route(
            "/admin/commerce/orders/{order_id}/payment-attempts",
            get(commerce::list_commerce_payment_attempts_handler),
        )
        .route(
            "/admin/commerce/orders/{order_id}/refunds",
            get(commerce::list_commerce_refunds_handler)
                .post(commerce::create_commerce_refund_handler),
        )
        .route(
            "/admin/commerce/orders/{order_id}/audit",
            get(commerce::get_commerce_order_audit_handler),
        )
        .route(
            "/admin/commerce/webhook-inbox",
            get(commerce::list_commerce_webhook_inbox_handler),
        )
        .route(
            "/admin/commerce/webhook-inbox/{webhook_inbox_id}/delivery-attempts",
            get(commerce::list_commerce_webhook_delivery_attempts_handler),
        )
        .route(
            "/admin/commerce/reconciliation-runs",
            get(commerce::list_commerce_reconciliation_runs_handler)
                .post(commerce::create_commerce_reconciliation_run_handler),
        )
        .route(
            "/admin/commerce/reconciliation-runs/{reconciliation_run_id}/items",
            get(commerce::list_commerce_reconciliation_items_handler),
        )
}
