use super::*;

pub(super) fn register_marketing_routes(router: Router<AdminApiState>) -> Router<AdminApiState> {
    router
        .route(
            "/admin/marketing/coupon-templates",
            get(marketing::list_marketing_coupon_templates_handler)
                .post(marketing::create_marketing_coupon_template_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/clone",
            post(marketing::clone_marketing_coupon_template_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/status",
            post(marketing::update_marketing_coupon_template_status_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/compare",
            post(marketing::compare_marketing_coupon_templates_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/submit-for-approval",
            post(marketing::submit_marketing_coupon_template_for_approval_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/approve",
            post(marketing::approve_marketing_coupon_template_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/reject",
            post(marketing::reject_marketing_coupon_template_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/publish",
            post(marketing::publish_marketing_coupon_template_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/schedule",
            post(marketing::schedule_marketing_coupon_template_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/retire",
            post(marketing::retire_marketing_coupon_template_handler),
        )
        .route(
            "/admin/marketing/coupon-templates/{coupon_template_id}/lifecycle-audits",
            get(marketing::list_marketing_coupon_template_lifecycle_audits_handler),
        )
        .route(
            "/admin/marketing/campaigns",
            get(marketing::list_marketing_campaigns_handler)
                .post(marketing::create_marketing_campaign_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/clone",
            post(marketing::clone_marketing_campaign_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/status",
            post(marketing::update_marketing_campaign_status_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/compare",
            post(marketing::compare_marketing_campaigns_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/submit-for-approval",
            post(marketing::submit_marketing_campaign_for_approval_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/approve",
            post(marketing::approve_marketing_campaign_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/reject",
            post(marketing::reject_marketing_campaign_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/publish",
            post(marketing::publish_marketing_campaign_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/schedule",
            post(marketing::schedule_marketing_campaign_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/retire",
            post(marketing::retire_marketing_campaign_handler),
        )
        .route(
            "/admin/marketing/campaigns/{marketing_campaign_id}/lifecycle-audits",
            get(marketing::list_marketing_campaign_lifecycle_audits_handler),
        )
        .route(
            "/admin/marketing/budgets",
            get(marketing::list_marketing_budgets_handler)
                .post(marketing::create_marketing_budget_handler),
        )
        .route(
            "/admin/marketing/budgets/{campaign_budget_id}/activate",
            post(marketing::activate_marketing_campaign_budget_handler),
        )
        .route(
            "/admin/marketing/budgets/{campaign_budget_id}/status",
            post(marketing::update_marketing_budget_status_handler),
        )
        .route(
            "/admin/marketing/budgets/{campaign_budget_id}/close",
            post(marketing::close_marketing_campaign_budget_handler),
        )
        .route(
            "/admin/marketing/budgets/{campaign_budget_id}/lifecycle-audits",
            get(marketing::list_marketing_campaign_budget_lifecycle_audits_handler),
        )
        .route(
            "/admin/marketing/codes",
            get(marketing::list_marketing_coupon_codes_handler)
                .post(marketing::create_marketing_coupon_code_handler),
        )
        .route(
            "/admin/marketing/codes/{coupon_code_id}/disable",
            post(marketing::disable_marketing_coupon_code_handler),
        )
        .route(
            "/admin/marketing/codes/{coupon_code_id}/status",
            post(marketing::update_marketing_coupon_code_status_handler),
        )
        .route(
            "/admin/marketing/codes/{coupon_code_id}/restore",
            post(marketing::restore_marketing_coupon_code_handler),
        )
        .route(
            "/admin/marketing/codes/{coupon_code_id}/lifecycle-audits",
            get(marketing::list_marketing_coupon_code_lifecycle_audits_handler),
        )
        .route(
            "/admin/marketing/reservations",
            get(marketing::list_marketing_coupon_reservations_handler),
        )
        .route(
            "/admin/marketing/redemptions",
            get(marketing::list_marketing_coupon_redemptions_handler),
        )
        .route(
            "/admin/marketing/rollbacks",
            get(marketing::list_marketing_coupon_rollbacks_handler),
        )
}
